package view;


import Controlador.ControladorLote;
import Controlador.ControladorMain;
import Models.conexion;
import java.io.BufferedWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;  
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
           
public class main extends javax.swing.JFrame {
    //Variable para controlar los forms //Es global
    public int presionado=0;
    public main() {
       initComponents();
       conexion os = new conexion();
      
       this.btn_acepConfigProd.setVisible(false);
       this.btn_configMort.setVisible(false);
       this.btn_aceptedConfigAli.setVisible(false);
       this.btn_aceptGeneral.setVisible(false);
       this.btn_modProd.setVisible(false);
       this.btn_modDatos.setVisible(false);
       this.btn_modAlimen.setVisible(false);
       this.btn_modMort.setVisible(false);
       this.LB_IdDespues.setVisible(false);
       this.LB_ID.setVisible(false);
       this.lb_loteAnt.setVisible(false);
       this.lb_idLote.setVisible(false);
       this.lb_cantAloHembras1.setVisible(false);
       this.lb_cantAloMachos1.setVisible(false);
       ControladorMain mn = new ControladorMain(this);
       ControladorLote lt = new ControladorLote(this);
       setIconImage(new ImageIcon(getClass().getResource("/img/logo2.jpeg")).getImage());
       this.Lote.setIconImage(new ImageIcon(getClass().getResource("/img/logo2.jpeg")).getImage());
       this.Lote.setTitle("Configuración General 'LOTES'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lote = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_lote = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_HembrasIniciadas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_MachosIniciados = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_HembrasAlojadas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_MachosAlojados = new javax.swing.JTextField();
        cbx_lotes = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        btn_AceptarLote = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_editarLote = new javax.swing.JButton();
        btn_registrarLote = new javax.swing.JButton();
        Calen_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        lb_idLote = new javax.swing.JLabel();
        lb_loteAnt = new javax.swing.JLabel();
        lb_advertencia2 = new javax.swing.JLabel();
        lb_advertencia1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txt_diaMacho = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_selMacho = new javax.swing.JTextField();
        txt_ventasMachos = new javax.swing.JTextField();
        txt_promedioMacho = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btn_configMort = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txt_diaHembra = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_selHembra = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_promedioHembra = new javax.swing.JTextField();
        txt_vetntasHembra = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_kgHembra = new javax.swing.JTextField();
        txt_grsHembra = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_kgMacho = new javax.swing.JTextField();
        txt_grsMacho = new javax.swing.JTextField();
        btn_aceptedConfigAli = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        txt_total1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_promedioTotal1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_INC = new javax.swing.JTextField();
        txt_promedioINC = new javax.swing.JTextField();
        btn_acepConfigProd = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txt_comercio = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txt_roto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cantHembras = new javax.swing.JTextField();
        txt_canMachos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        btn_modMort = new javax.swing.JButton();
        btn_modDatos = new javax.swing.JButton();
        btn_modAlimen = new javax.swing.JButton();
        btn_modProd = new javax.swing.JButton();
        btn_aceptGeneral = new javax.swing.JButton();
        cbx_tablas = new javax.swing.JComboBox<>();
        LB_ID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_cantAloHembras = new javax.swing.JLabel();
        lb_cantAloMachos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_config = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        LB_lote = new javax.swing.JLabel();
        lb_cantAloHembras1 = new javax.swing.JLabel();
        lb_cantAloMachos1 = new javax.swing.JLabel();
        LB_IdDespues = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_main = new javax.swing.JTable();
        btn_VerGenral = new javax.swing.JButton();

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lotes Anteriores:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, -1));

        txt_lote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(txt_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 140, 25));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de Nacimiento:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txt_HembrasIniciadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(txt_HembrasIniciadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 140, 25));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hembras Iniciadas: ");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txt_MachosIniciados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(txt_MachosIniciados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, 25));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Machos Iniciados: ");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Hembras Alojadas:");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txt_HembrasAlojadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(txt_HembrasAlojadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 140, 25));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Machos Alojados:");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txt_MachosAlojados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(txt_MachosAlojados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 140, 25));

        jPanel7.add(cbx_lotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, 30));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("No. Lote: ");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        btn_AceptarLote.setBackground(new java.awt.Color(153, 0, 0));
        btn_AceptarLote.setForeground(new java.awt.Color(255, 255, 255));
        btn_AceptarLote.setText("Aceptar");
        btn_AceptarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarLoteActionPerformed(evt);
            }
        });
        jPanel7.add(btn_AceptarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 90, -1));

        btn_nuevo.setBackground(new java.awt.Color(153, 0, 0));
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("Nuevo");
        jPanel7.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 90, -1));

        btn_editarLote.setBackground(new java.awt.Color(153, 0, 0));
        btn_editarLote.setForeground(new java.awt.Color(255, 255, 255));
        btn_editarLote.setText("Editar");
        jPanel7.add(btn_editarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, -1));

        btn_registrarLote.setBackground(new java.awt.Color(153, 0, 0));
        btn_registrarLote.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarLote.setText("Registrar");
        jPanel7.add(btn_registrarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 90, -1));

        Calen_fechaNacimiento.setDateFormatString("dd/MM/yyyy");
        jPanel7.add(Calen_fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, 30));
        jPanel7.add(lb_idLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 30));
        jPanel7.add(lb_loteAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 50, 30));

        lb_advertencia2.setForeground(new java.awt.Color(255, 255, 255));
        lb_advertencia2.setText("Una vez Ingresados ya NO se podran Modificar.");
        jPanel7.add(lb_advertencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 360, 30));

        lb_advertencia1.setForeground(new java.awt.Color(255, 255, 255));
        lb_advertencia1.setText("Verifique Hembras y Machos Alojados esten correctos.");
        jPanel7.add(lb_advertencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 380, 30));

        jPanel10.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 300, 290));

        javax.swing.GroupLayout LoteLayout = new javax.swing.GroupLayout(Lote.getContentPane());
        Lote.getContentPane().setLayout(LoteLayout);
        LoteLayout.setHorizontalGroup(
            LoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoteLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LoteLayout.setVerticalGroup(
            LoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoteLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reporte Diario de Producción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mortalidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(153, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(153, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Dia");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, -1, -1));

        txt_diaMacho.setText("0");
        jPanel6.add(txt_diaMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 41, 48, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SEL");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 70, -1, -1));

        txt_selMacho.setText("0");
        jPanel6.add(txt_selMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 93, 48, -1));

        txt_ventasMachos.setText("0");
        jPanel6.add(txt_ventasMachos, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 93, 90, -1));

        txt_promedioMacho.setEditable(false);
        jPanel6.add(txt_promedioMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 41, 90, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Ventas");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 70, -1, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("%");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 18, -1, -1));

        btn_configMort.setBackground(new java.awt.Color(0, 0, 0));
        btn_configMort.setForeground(new java.awt.Color(255, 255, 255));
        btn_configMort.setText("Aceptar");
        btn_configMort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configMortActionPerformed(evt);
            }
        });
        jPanel6.add(btn_configMort, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 18, 190, 170));

        jPanel12.setBackground(new java.awt.Color(153, 0, 0));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hembras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel12.setForeground(new java.awt.Color(153, 0, 0));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Dia");

        txt_diaHembra.setText("0");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("%");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("SEL");

        txt_selHembra.setText("0");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ventas");

        txt_promedioHembra.setEditable(false);

        txt_vetntasHembra.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(txt_diaHembra, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(txt_selHembra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_vetntasHembra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_promedioHembra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(57, 57, 57))))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diaHembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_promedioHembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_selHembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vetntasHembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, 170));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 420, 200));

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alimentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(153, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hembras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(153, 0, 0));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("KG");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("GRS");

        txt_kgHembra.setText("0");

        txt_grsHembra.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_kgHembra)
                    .addComponent(txt_grsHembra)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel14)
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kgHembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_grsHembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, 178));

        jPanel11.setBackground(new java.awt.Color(153, 0, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("KG");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("GRS");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txt_kgMacho.setText("0");
        jPanel11.add(txt_kgMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 91, -1));

        txt_grsMacho.setEditable(false);
        jPanel11.add(txt_grsMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 91, -1));

        btn_aceptedConfigAli.setBackground(new java.awt.Color(0, 0, 0));
        btn_aceptedConfigAli.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptedConfigAli.setText("Aceptar");
        jPanel11.add(btn_aceptedConfigAli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 18, 130, 180));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 286, 204));

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comercio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(153, 0, 0));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de Huevos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel13.setForeground(new java.awt.Color(153, 0, 0));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Total");

        txt_total1.setText("0");

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("%");

        txt_promedioTotal1.setEditable(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel40))
                    .addComponent(jLabel39))
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(txt_promedioTotal1)
            .addComponent(txt_total1)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_promedioTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 18, -1, 178));

        jPanel14.setBackground(new java.awt.Color(153, 0, 0));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incubables", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel14.setForeground(new java.awt.Color(153, 0, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("INC");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("%");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txt_INC.setText("0");
        jPanel14.add(txt_INC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, -1));

        txt_promedioINC.setEditable(false);
        jPanel14.add(txt_promedioINC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, -1));

        btn_acepConfigProd.setBackground(new java.awt.Color(0, 0, 0));
        btn_acepConfigProd.setForeground(new java.awt.Color(255, 255, 255));
        btn_acepConfigProd.setText("Aceptar");
        jPanel14.add(btn_acepConfigProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 18, 130, 180));

        jPanel16.setBackground(new java.awt.Color(153, 0, 0));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Negocio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel16.setForeground(new java.awt.Color(153, 0, 0));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Comercio");

        txt_comercio.setText("0");

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Rotos");

        txt_roto.setText("0");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel38))
                    .addComponent(jLabel37))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_roto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_comercio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(txt_comercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_roto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, 178));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 381, 200));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel2.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hembras");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel2.add(txt_cantHembras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, -1));
        jPanel2.add(txt_canMachos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 92, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Machos");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        btn_Agregar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Agregar.setText("Agregar Registro");
        jPanel2.add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        btn_modMort.setBackground(new java.awt.Color(0, 0, 0));
        btn_modMort.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_modMort.setForeground(new java.awt.Color(255, 255, 255));
        btn_modMort.setText("Modificar Mortalidad");
        btn_modMort.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_modMort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modMort.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modMort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modMortActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modMort, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        btn_modDatos.setBackground(new java.awt.Color(0, 0, 0));
        btn_modDatos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_modDatos.setForeground(new java.awt.Color(255, 255, 255));
        btn_modDatos.setText("Modificar Datos");
        btn_modDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_modDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modDatosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        btn_modDatos.getAccessibleContext().setAccessibleDescription("");

        btn_modAlimen.setBackground(new java.awt.Color(0, 0, 0));
        btn_modAlimen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_modAlimen.setForeground(new java.awt.Color(255, 255, 255));
        btn_modAlimen.setText("Modificar Alimentos");
        btn_modAlimen.setActionCommand("Medicamentos");
        btn_modAlimen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_modAlimen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modAlimen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modAlimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modAlimenActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modAlimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        btn_modProd.setBackground(new java.awt.Color(0, 0, 0));
        btn_modProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_modProd.setForeground(new java.awt.Color(255, 255, 255));
        btn_modProd.setText("Modificar Producción");
        btn_modProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_modProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modProd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modProdActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, -1, -1));

        btn_aceptGeneral.setBackground(new java.awt.Color(0, 0, 0));
        btn_aceptGeneral.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptGeneral.setText("Aceptar");
        jPanel2.add(btn_aceptGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 123, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 1360, 250));

        cbx_tablas.setBackground(new java.awt.Color(153, 0, 0));
        cbx_tablas.setForeground(new java.awt.Color(255, 255, 255));
        cbx_tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATOS GENERALES", "EXISTENCIA", "MORTALIDAD", "ALIMENTOS", "PRODUCCIÓN" }));
        getContentPane().add(cbx_tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 253, -1));
        getContentPane().add(LB_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 39, 57, 22));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hembras Alojadas: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Machos Alojados: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        lb_cantAloHembras.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_cantAloHembras, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 50, 30));

        lb_cantAloMachos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_cantAloMachos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 50, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Producción");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        btn_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config.png"))); // NOI18N
        btn_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configActionPerformed(evt);
            }
        });
        jPanel1.add(btn_config, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 43, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Lote: ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 30));

        LB_lote.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LB_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 60, 30));

        lb_cantAloHembras1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_cantAloHembras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 50, 30));

        lb_cantAloMachos1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_cantAloMachos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 0, 450, -1));
        getContentPane().add(LB_IdDespues, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 60, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpeg"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(153, 0, 0));

        tb_main.setBackground(new java.awt.Color(153, 0, 0));
        tb_main.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tb_main.setForeground(new java.awt.Color(255, 255, 255));
        tb_main.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Edad", "Cant. Hembras", "Cant. Machos", "Mort. Hembras", "Mort. Machos", "Alimento Hembras", "Alimento Machos", "Total Huevos", "Incubables", "Comercializar", "Huevos Rotos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_main.setFocusable(false);
        tb_main.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_main.setRowHeight(20);
        tb_main.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tb_main.setShowHorizontalLines(false);
        tb_main.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tb_main);

        btn_VerGenral.setBackground(new java.awt.Color(153, 0, 0));
        btn_VerGenral.setForeground(new java.awt.Color(255, 255, 255));
        btn_VerGenral.setText("Ver Tabla General");
        btn_VerGenral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerGenralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btn_VerGenral)
                        .addGap(616, 616, 616))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(btn_VerGenral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modDatosActionPerformed
        // TODO add your handling code here:
        this.btn_aceptedConfigAli.setVisible(false);
        this.btn_acepConfigProd.setVisible(false);
        this.btn_configMort.setVisible(false);
        this.btn_aceptGeneral.setVisible(true);
    }//GEN-LAST:event_btn_modDatosActionPerformed

    private void btn_modMortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modMortActionPerformed
        // TODO add your handling code here:
        this.btn_aceptedConfigAli.setVisible(false);
        this.btn_acepConfigProd.setVisible(false);
        this.btn_configMort.setVisible(true);
        this.btn_aceptGeneral.setVisible(false);
    }//GEN-LAST:event_btn_modMortActionPerformed

    private void btn_modAlimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modAlimenActionPerformed
        // TODO add your handling code here:
        this.btn_aceptedConfigAli.setVisible(true);
        this.btn_acepConfigProd.setVisible(false);
        this.btn_configMort.setVisible(false);
        this.btn_aceptGeneral.setVisible(false);
    }//GEN-LAST:event_btn_modAlimenActionPerformed

    private void btn_modProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modProdActionPerformed
        // TODO add your handling code here:
        this.btn_acepConfigProd.setVisible(true);
        this.btn_aceptedConfigAli.setVisible(false);
        this.btn_configMort.setVisible(false);
        this.btn_aceptGeneral.setVisible(false);
    }//GEN-LAST:event_btn_modProdActionPerformed

    private void btn_configMortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configMortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_configMortActionPerformed

    private void btn_VerGenralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerGenralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VerGenralActionPerformed

    private void btn_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configActionPerformed
        
    }//GEN-LAST:event_btn_configActionPerformed

    private void btn_AceptarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarLoteActionPerformed
       
    }//GEN-LAST:event_btn_AceptarLoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser Calen_fechaNacimiento;
    public javax.swing.JLabel LB_ID;
    public javax.swing.JLabel LB_IdDespues;
    public javax.swing.JLabel LB_lote;
    public javax.swing.JFrame Lote;
    public javax.swing.JButton btn_AceptarLote;
    public javax.swing.JButton btn_Agregar;
    public javax.swing.JButton btn_VerGenral;
    public javax.swing.JButton btn_acepConfigProd;
    public javax.swing.JButton btn_aceptGeneral;
    public javax.swing.JButton btn_aceptedConfigAli;
    public javax.swing.JButton btn_config;
    public javax.swing.JButton btn_configMort;
    public javax.swing.JButton btn_editarLote;
    public javax.swing.JButton btn_modAlimen;
    public javax.swing.JButton btn_modDatos;
    public javax.swing.JButton btn_modMort;
    public javax.swing.JButton btn_modProd;
    public javax.swing.JButton btn_nuevo;
    public javax.swing.JButton btn_registrarLote;
    public javax.swing.JComboBox<String> cbx_lotes;
    public javax.swing.JComboBox<String> cbx_tablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lb_advertencia1;
    public javax.swing.JLabel lb_advertencia2;
    public javax.swing.JLabel lb_cantAloHembras;
    public javax.swing.JLabel lb_cantAloHembras1;
    public javax.swing.JLabel lb_cantAloMachos;
    public javax.swing.JLabel lb_cantAloMachos1;
    public javax.swing.JLabel lb_idLote;
    public javax.swing.JLabel lb_loteAnt;
    public javax.swing.JTable tb_main;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txt_HembrasAlojadas;
    public javax.swing.JTextField txt_HembrasIniciadas;
    public javax.swing.JTextField txt_INC;
    public javax.swing.JTextField txt_MachosAlojados;
    public javax.swing.JTextField txt_MachosIniciados;
    public javax.swing.JTextField txt_canMachos;
    public javax.swing.JTextField txt_cantHembras;
    public javax.swing.JTextField txt_comercio;
    public javax.swing.JTextField txt_diaHembra;
    public javax.swing.JTextField txt_diaMacho;
    public javax.swing.JTextField txt_fecha;
    public javax.swing.JTextField txt_grsHembra;
    public javax.swing.JTextField txt_grsMacho;
    public javax.swing.JTextField txt_kgHembra;
    public javax.swing.JTextField txt_kgMacho;
    public javax.swing.JTextField txt_lote;
    public javax.swing.JTextField txt_promedioHembra;
    public javax.swing.JTextField txt_promedioINC;
    public javax.swing.JTextField txt_promedioMacho;
    public javax.swing.JTextField txt_promedioTotal1;
    public javax.swing.JTextField txt_roto;
    public javax.swing.JTextField txt_selHembra;
    public javax.swing.JTextField txt_selMacho;
    public javax.swing.JTextField txt_total1;
    public javax.swing.JTextField txt_ventasMachos;
    public javax.swing.JTextField txt_vetntasHembra;
    // End of variables declaration//GEN-END:variables
}
